import type { Metadata } from "next";
import Header from "@/components/shared/nav";
import "./globals.css";
import { Work_Sans } from "next/font/google";
import Footer from "@/components/shared/footer";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
